pipeline {
agent any

```
environment {
    DOCKER_USERNAME = ''
    IMAGE_NAME = ''
    DOCKER_CREDS = ''
}

tools {
    nodejs 'node18'
}

stages {

    stage('Checkout Source Code') {
        steps {
            echo 'Cloning repository from GitHub...'
            git 'https://github.com/your-username/your-repo.git'
        }
    }

    stage('Install Dependencies') {
        steps {
            dir('jenkins-frontend') {
                sh 'npm install'
            }
        }
    }

    stage('Build React App') {
        steps {
            dir('jenkins-frontend') {
                sh 'npm run build'
            }
        }
    }

    stage('Build Docker Image') {
        steps {
            echo 'Building Docker Image...'
            sh 'docker build -t $DOCKER_USERNAME/$IMAGE_NAME .'
        }
    }

    stage('Login to Docker Hub') {
        steps {
            withCredentials([usernamePassword(
                credentialsId: "$DOCKER_CREDS",
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )]) {
                sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
            }
        }
    }

    stage('Push Docker Image') {
        steps {
            echo 'Pushing Docker Image to Docker Hub...'
            sh 'docker push $DOCKER_USERNAME/$IMAGE_NAME'
        }
    }

    stage('Success') {
        steps {
            echo 'Docker Image Successfully Pushed to Docker Hub!'
        }
    }
}
```

}
