pipeline {
    agent any

    tools {
        nodejs 'node18' 
    }

    stages {

        stage('Clone Repository') {
            steps {
                echo 'Cloning repository...'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build React App') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Success') {
            steps {
                echo 'Build Successful '
            }
        }
    }
}